import './globals.css'
import { Inter } from 'next/font/google'
import ComplexNavbar from './NavBar'
import Footer from './Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "David's Blog",
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="\Blog.ico" sizes='any'/>
      </head>
      <body className={`${inter.className} bg-gradient-to-b from-white to-white w-full`}>
        <ComplexNavbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
